name: Bug 反馈
description: 当你在使用时发现了一个 Bug，或者某些地方看起来不对劲。
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: 这个问题是否已经存在？
      options:
        - label: 我已经搜索过现有的问题 (https://github.com/jingsong2008/dcbot/issues)
          required: true
  - type: textarea
    attributes:
      label: 如何复现
      description: 请详细告诉我们如何复现你遇到的问题。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 预期结果
      description: 请告诉我们你预期会发生什么。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 实际结果
      description: 请告诉我们实际发生了什么。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 截图或视频
      description: 如果可以的话，上传任何关于 bug 的截图。
